version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: Api/Dockerfile
    ports:
      - published: 80
        target: 80
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      RATE_LIMIT_SECONDS: 0

  redis:
    image: redis
    ports:
      - published: 6379
        target: 6379
